
---
Trying to do the automatic from google scholar, but no dice so far. 
title: Publications
date: 2022-07-15
draft: true
excerpt: Publications, book chapters, and reports

---

```{r include = FALSE, echo=FALSE, message=FALSE, warning=FALSE}
library(scholar)
library(tidyverse)

publications <- as_tibble(get_publications("PdcTYyYAAAAJ")) %>%
  arrange(desc(year)) %>%
  mutate(author_long =
           case_when(str_detect(author, pattern = "\\.\\.\\.$") ~ 1, TRUE ~ 0)) %>%
  mutate(author = case_when(
    author_long == 1 ~ get_complete_authors("PdcTYyYAAAAJ", pubid),
    TRUE ~ author
  )) %>%
  mutate(
    author = str_replace_all(author, "([A-Z]) ([A-Z]) ", "\\1\\2 "),
    author = str_replace_all(author, "JLA Dykxhoorn", "**JLA Dykxhoorn**"),
    author = str_replace_all(author, "J Dykxhoorn", "**J Dykxhoorn**"),
    title = str_replace_all(title, ":.+", "")
  ) %>%
  split(desc(.$year)) %>%
  map(function(x) {
    x <- x %>%
      mutate(
        citation = paste0(
          author,
          ". ",
          "(",
          year,
          ").",
          " ",
          "[",
          title,
          "]",
          "(https://scholar.google.com/scholar?oi=bibs&cluster=",
          cid,
          "&btnI=1&hl=en)",
          ". ",
          "*",
          journal,
          "*",
          " ",
          number,
          "."
        )
      ) %>%
      select(citation)
    return(x)
  })

publications <-
  map2(substring(names(publications), 2) %>% paste0("<h2>", ., "</h2>"),
       publications,
       c) %>% unlist %>% as_tibble() %>%  mutate(value = gsub("Rv Kessel", "R van Kessel", value)) %>% pivot_wider(names_from = value) 
```

```{r results = 'asis', echo=FALSE, message=FALSE, warning=FALSE}
cat(paste0(publications), sep = "  \n")
```
