---
title: Maps and anti-racism
author: Jen Dykxhoorn
date: '2022-09-15'
draft: true
slug: []
categories: []
tags: []
---

I love a good map. I spent hours (days? weeks?) in lockdown cross-stitching an elaborate floral map of the world. 


## Maps change the way we see the world
They are not only representations of the physical world, but they also communicate how we see the world. 

The map that was on every classroom wall was a Mercador projection. 

The Mercador projection owes its origin to the pope, who commissioned Mercador to map the spread of Christianity. 

The tricky thing is how to turn something round into something flat. This means you will need to make choices about what aspects of the world are most important to depict accurately and which you can ____

This means that you have to make many judgements and assuptions about what are the most important aspects of the map to caputre accurately. 

What may seem like a benign representation of the physical world is not quite so innocent. (political implications of map design) 

## Equal-area map projection - Gall-Peters Projection

In the 19th century, the Gall-Peters projection (aka Peters' projection) emerged as a more realistic way of pre4senting the world by keeping the real proportions between continent sizes. It was proposed by James Gall in 1855. (interestingly, Gall was ALSO a clergyman - it seems the religious folk had a great deal of interest in mapping). Arno Peters, a German filmmaker, had proposed a similar projection in 1967, which he present4ed as the "Peters world map" 

Also called an "equal-area" projection map, becaues it focuses on accurately depicting the area, resulting in distortions of shapes. 

Peters started campaigning against the Mercator projection, claiming that it was the only projection with is "area-correct," which was inaccurate, considering the long cartographic history of projections. It is possible that his aggresssive insistence on the superiority of the "Peters projection" over the Mercator created an academic impass, and were never able to reach any sort of middle ground. Ironically, these cartographic debates had a polarizing effect on the mapping community, although his focus on the political nature of maps may have furthered the conversation that we are continuing to have today. 




## Winkel Tripel projection (Winkel III)
I think the Winkel is now my favourite map projection (not jsut because it is fun to say), as it represents a balance between the dominant Mercator and the domineering Gall-Peters projections.

The immediate difference is that the map is not stretched to a satisfying rectangular shape, which works well for a wall map, but is a 

Winkel Tripel projection (1921)- a compromise between the Gall-Peters and Mercator projections by finding a balance between the distortions of relative surfaces and those in length and distnace - used since 1998 by the National Geographic Society, as it balances landmass and curvature 



The Ginzburg V (1950) is also a satisfying option - 

(map-projections.net)




Look at the Tissot's indicatrix to characterise the distortions due to map rpojection. 



