---
title: Trajectories of deprivation and population density before and after diagnosis
  with a psychotic disorder
author: "J Dykxhoorn"
date: "2023-10-15"
categories:
- New research
- Longitudinal
- Epidemiology
- Psychosis
- Deprivation
- Population density
- Sweden
excerpt: Does exposure to differing trajectories of deprivation and population density
  affect rates of psychotic disorders?
draft: no
series: null
layout: single
image_left: yes
featured: yes
show_post_thumbnail: yes
---

People with psychosis are more likely to live in densely populated, socioeconomically deprived areas. However, it is not clear if the relationship between these environmental risk factors and psychosis are due to causation or social drift. 

For example, the high rates of psychotic disorders among those living in crowded, deprived areas may be because these environmental risk factors cause psychotic disorders. 

Alternately, people with psychotic disorders may experience downward social mobility, drifting to areas with more deprivation (social drift). This may even happen between generations, where individuals with genetic predispositions to psychosis or cognitive impairments may be more likely to live in highly dense and deprived areas (social selection).

Finally, people with psychosis may be more likely to remain in the same neighbourhood, experiencing social immobility, than their peers without psychosis. 

Interestingly, previous research suggests that the relationship between environmental risk factors (deprivation and population density) are more strongly related to psychotic disorders (including schizophrenia) than other severe mental illnesses, like non-psychotic bipolar disorder. 


## Research question
Were trajectories (patterns) of exposure to deprivation and population density associated with psychotic disorders or non-psychotic bipolar disorder? 


## What did we do? 
This study looked at people born in Sweden between 1982 and 2001. We identified all those diagnosed with a psychotic disorder or non-psychotic bipolar disorder after age 15 (cases). We identified over 26,000 cases. 

We matched each case with a control person of the same sex and birth year who has not been diagnosed with a psychotic disorder or non-psychotic bipolar disorder (controls). This meant we had over 26,000 controls. 


## Nitty-gritty details of the analysis
 We used group-based trajectory modelling group people who had similar experiences of living in deprived or densely populated places over time. We grouped people based on exposure to these environmental risk factors before diagnosis (between birth and age 14) and after diagnosis (from the diagnosis year to the end of the follow-up period).

This [hopefully] makes more sense when you look at the figures. Here, for example, you see the exposure to deprivation over time from birth through age 14 (pre-diagnosis period). There is one group (top in white) which experienced a high level of deprivation throughout this period . There is another group (bottom in dark blue) that never lived lived in a deprived area throughout their childhood. The other groups experienced change over time. Some groups (orange and grey) experienced deprivation early in their childhood, but this reduced over time (upward mobility). The other groups (e.g. light blue and brown) saw a gradual increase in their level of deprivation over time.

We generated similar trajectories for deprivation experienced after diagnosis, and for population density (before and after diagnosis).

Once each person was assigned their trajectory, we conducted logistic regression to explore the relationship between each exposure (deprivation / population density) before and after diagnosis and rates of psychotic disorders and non-psychotic bipolar disorder. 

## What did we find? 
We found evidence that living in more deprived and more densely populated areas from birth through early adolescence increased the odds of developing psychotic disorders. Those who experienced "upward mobility" during their upbringing had lower risk than those who had experienced persistently high levels of deprivation and population density. 

After diagnosis, those with a psychotic disorder were more likely than their matche dcontrol to be living in more deprived areas, and were more likely to "drift" downward to areas with more deprivation. Importantly, people with psychotic disorders were more likely to remain in the deprived areas (social immobility) compared to the control participants, who were likely to experience upward mobility over time. 

We found different patterns for non-psychotic bipolar disorder for deprivation and population density (see full paper for details).

## What does this mean? 
This research provides further evidence that experiencing highly deprived and densely populated environments during upbringing leads to higher rates of psychotic disorders, consistent with the "social causation" model. 

It also shows that people who have been diagnosed with psychotic disorders are likely to experience "social immobility," remaining in areas of high deprivation and density for years after their diagnosis, while those without psychosis are likely to experience upward mobility to more desirable areas. 

  This research shows that people with psychotic disorders are more likely to live in deprived and densely populated environments, and tend to remain in these areas following diagnosis. 

A very interesting finding was that the risk of psychosis among those who experienced deprivation in early childhood was ameliorated if their families experienced upward mobility during their upbringing. This may be an area for public health intervention, as social mobility may mitigate the impacts of early-life deprivation.  

## Read more
The full article was published open-access in JAMA Psychiatry and is available
[here](https://pubmed.ncbi.nlm.nih.gov/37672257/)

## Behind the research
This research was developed as part of Yanakan Logeswaran's MSc thesis and he worked closely with James Kirkbride to finalise the results for publication. Yan has gone on to begin a PhD at Kings College London's Institute of Psychiatry, Psychology, and Neuroscience. 
  